<?php

namespace Proxies\__CG__\PartKeepr\User;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \PartKeepr\User\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function setRawUsername($username)
    {
        $this->__load();
        return parent::setRawUsername($username);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setAdmin($bAdmin)
    {
        $this->__load();
        return parent::setAdmin($bAdmin);
    }

    public function isAdmin()
    {
        $this->__load();
        return parent::isAdmin();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getHashedPassword()
    {
        $this->__load();
        return parent::getHashedPassword();
    }

    public function setHashedPassword($hashedPassword)
    {
        $this->__load();
        return parent::setHashedPassword($hashedPassword);
    }

    public function comparePassword($password)
    {
        $this->__load();
        return parent::comparePassword($password);
    }

    public function compareHashedPassword($hashedPassword)
    {
        $this->__load();
        return parent::compareHashedPassword($hashedPassword);
    }

    public function serialize()
    {
        $this->__load();
        return parent::serialize();
    }

    public function deserialize(array $parameters)
    {
        $this->__load();
        return parent::deserialize($parameters);
    }

    public function setPreference($preferenceKey, $preferenceValue)
    {
        $this->__load();
        return parent::setPreference($preferenceKey, $preferenceValue);
    }

    public function getPreference($preferenceKey)
    {
        $this->__load();
        return parent::getPreference($preferenceKey);
    }

    public function getPreferenceValue($preferenceKey)
    {
        $this->__load();
        return parent::getPreferenceValue($preferenceKey);
    }

    public function deletePreference($preferenceKey)
    {
        $this->__load();
        return parent::deletePreference($preferenceKey);
    }

    public function getPreferences()
    {
        $this->__load();
        return parent::getPreferences();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function deserializeChildren(array $sourceArray, \Doctrine\Common\Collections\Collection $collection, $entityClass)
    {
        $this->__load();
        return parent::deserializeChildren($sourceArray, $collection, $entityClass);
    }

    public function serializeChildren(\Doctrine\Common\Collections\Collection $array)
    {
        $this->__load();
        return parent::serializeChildren($array);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'password', 'admin');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}