<?php

namespace Proxies\__CG__\PartKeepr\Statistic;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class StatisticSnapshotUnit extends \PartKeepr\Statistic\StatisticSnapshotUnit implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setStatisticSnapshot(\PartKeepr\Statistic\StatisticSnapshot $snapshot)
    {
        $this->__load();
        return parent::setStatisticSnapshot($snapshot);
    }

    public function getStatisticSnapshot()
    {
        $this->__load();
        return parent::getStatisticSnapshot();
    }

    public function setPartUnit(\PartKeepr\Part\PartUnit $unit)
    {
        $this->__load();
        return parent::setPartUnit($unit);
    }

    public function getPartUnit()
    {
        $this->__load();
        return parent::getPartUnit();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setStockLevel($stockLevel)
    {
        $this->__load();
        return parent::setStockLevel($stockLevel);
    }

    public function getStockLevel()
    {
        $this->__load();
        return parent::getStockLevel();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'stockLevel', 'statisticSnapshot', 'partUnit');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}